### PR TITLE
Track Section Added

### LINKED ISSUE #49: Tracks Section
*Important*: Work on tracks in a different branch since we'll add that to the site as soon as we post about it on social media

We can make the tracks section similar to this:
image

Source: https://trondao.org/

### LINKED ISSUE #58: Add discord button
This needs to be added as soon as discord server is made for 4.0

**Update**
Link to the discord server:
https://discord.gg/uKUZRFpx

### PR DESCRIPTION
**Pull request by Omega08**
Added track section. Let me know if some changes are required.

### CODE REVIEW

**Comment by soshar** [comment]
Hi @Omega08,
Great work!
The tracks are overflowing in x direction. Can you modify the section to have some tracks in the next row?

**Comment by Omega08** [comment]
I've modified the track section accordingly. Also added the discord button at the footer and changes to fa icons in the navbar with svgs. Please look into it and tell if anymore changes are required.

**Comment by soshar** [comment]
Great!
@Omega08 There is overflow on phone now in x direction, I dont think that's obvious. Can you move some contents to the next row?

**Comment by Omega08** [comment]
@Sharvani2002 Changed it.

**Comment by soshar** [comment]
@Omega08, cool. We haven't received updates from the technical team yet. Once we get to know the exact tracks, we can add them ASAP from this PR. Also, please make different PRs for different issues

**Pull request closed without merging**
